### ISSUE TITLE
Oct visit TODO

### ISSUE THREAD

**Issue by cekees** [erdc-cm/air-water-vv#22]
- [x] current road blocks with tests
- [x] linear solver options
- [x] air compressibility
- [x] turbulence modeling 
- [x] topics for talking  to wider HRW team
- [x] gauge redesign
- [x] compressibility issues
- [ ] Boussinesq
- [ ] archiving model output
- [x] wave/current generation road map and boundary conditions in general (go through how to set them)
- [ ] how to move forward with options that shouldn't effect the results  significantly
